[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  VUE_APP_API_KEY = "AIzaSyBQpk986QtxWMeYtX5__8TgYyx4NSTu_14"
  VUE_APP_FIREBASE_API_KEY = "AIzaSyBGiVPoxWm8ARS1oVvl1Dyv_c37c17Gtp8"
  VUE_APP_FIREBASE_AUTH_DOMAIN = "freeoguessr-firebase.firebaseapp.com"
  VUE_APP_FIREBASE_DATABASE_URL = "https://freeoguessr-firebase-default-rtdb.europe-west1.firebasedatabase.app"
  VUE_APP_FIREBASE_PROJECT_ID = "freeoguessr-firebase"
  VUE_APP_STORAGE_BUCKET = "freeoguessr-firebase.appspot.com"
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID = "14128027931"
  VUE_APP_FIREBASE_APP_ID = "1:14128027931:web:179af081a9fc5158d01bbe"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200